language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t vincentyuuu/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true vincentyuuu/docker-react-practice yarn test